### ISSUE TITLE
Repo missing stringdata.cpp, writer.cpp, and contentiterator.cpp? Possibly missing other .cpps too?

### ISSUE THREAD

**Issue by Starkeus** [shreaker/OpenXCP#4]
Hi,
Trying to run this on Ubuntu, and qtcreator 6.0.2 throws errors requesting cpp files as the implementation match is not there for QtCSV::StringData and QtCSV::Write. Looks like you have also modified it from the general qtcsv implementation, so would appreciate those files to test some XCP on my end. 

Also, does this base work where I can connect a Linux PC to a Vector VX to perform XCP over Ethernet? (PC Master and VX slave). Any thoughts on how to do that is appreciated too.

**Comment by Starkeus** [comment]
Also, where is qtcsv.pro to build the qtcsv files?

**Comment by Starkeus** [comment]
XCP_Master/source/main/backend.cpp:205: error: undefined reference to `QtCSV::StringData::StringData()'

XCP_Master/build-Qt_Open_XCP-Desktop-Debug/../source/main/backend.cpp:237: undefined reference to `QtCSV::StringData::addRow(QStringList const&)'

XCP_Master/build-Qt_Open_XCP-Desktop-Debug/../source/main/backend.cpp:252: undefined reference to `QtCSV::StringData::~StringData()'

XCP_Master/build-Qt_Open_XCP-Desktop-Debug/../source/main/backend.cpp:252: undefined reference to `QtCSV::StringData::~StringData()'

XCP_Master/source/main/backend.cpp:292: error: undefined reference to `QtCSV::Writer::write(QString const&, QtCSV::AbstractData const&, QString const&, QString const&, QtCSV::Writer::WriteMode const&, QStringList const&, QStringList const&, QTextCodec*)'

Errors because of not having stringdata.cpp and writer.cpp.

Michael, can I please have these source files and possibly even email you about these?

**Comment by yuan9931** [comment]
QtCSV is another lib which is used but not include in this project. You can download the lib(debug directory) from others or build the qtcsv lib, then add it into your own project. For me, I just comment out the code which uses the lib.

**Comment by Starkeus** [comment]
Sounds good.
I was able to create these files and perform an initial compilation.
I want to know where the DAQ commands are sent? (Like a series that I see on wireshark such as 02 00 00 **01** ff 00 followed by  02 00 00 **02** ff 00 and  02 00 00 **03** ff 00 )
